import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import TodoList from '../components/TodoList'
import UserList from '../components/UserList'
import s from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <UserList />
        <hr />
        <TodoList />
      </main>
    </div>
  )
}

export default Home
